name: Integration test
on:
  - push
  - pull_request

jobs:
  test:
    name: Run tests
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        drupal-version:
          - "^10"
          - "^11"
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Update composer
        run: composer --verbose self-update --2

      - name: Dump composer version
        run: composer --version

      - name: Install Drupal
        run: |
          composer create-project "drupal/recommended-project:${{ matrix.drupal-version }}" drupal
          cd drupal
          # Require our package from the parent folder
          composer config repositories."build-drupal-wasm" path ".."
          # Allow our dev things, since a branch or PR will of course always be dev.
          composer config minimum-stability dev
          # We are about to require a plugin as well, so let's allow that
          composer config --no-plugins allow-plugins true
          composer require "eiriksm/build-drupal-wasm"
